# Generated by Django 4.2.2 on 2023-07-10 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_folder_files_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='folder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myApp.folder'),
        ),
    ]
