# Generated by Django 4.2.2 on 2023-07-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_files_datetime_alter_files_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='datetime',
        ),
        migrations.AddField(
            model_name='files',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
